LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := GrapheneCamera
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Camera.apk
LOCAL_PACKAGE_NAME := Camera
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Snap Camera Camera2
LOCAL_PRODUCT_MODULE := true
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.camera.extensions.impl

include $(BUILD_PREBUILT)
